server:
  port: 8081

#spring:
#  redis:
#    host: localhost
#    port: 6379
#  session:
#    store-type: redis

spring:
  data:
    redis:
      host: localhost
      port: 6379
  session:
    store-type: redis